name: MediaMTX Proxy
version: "1.13.0"
slug: mediamtx
description: Lightweight RTSP/RTMP/WEBRTC stream relay for Home Assistant
startup: services
boot: auto
hassio_api: false
host_network: true
hassio_role: default

options: {}

schema: {}

ports:
  8554/tcp: 8554  # RTSP
  1935/tcp: 1935  # RTMP
  8888/tcp: 8888  # Web UI
  8889/tcp: 8889
  8890/udp: 8890
  8189/udp: 8189
